### PR TITLE
Mocap support restruct

### PR DESCRIPTION
**Pull request by congleetea**

### CODE REVIEW

**Comment by congleetea** [comment]
mocap_support:update to debug log structure

**Comment by TSC21** [comment]
@congleetea what's the purpose of this?

**Comment by congleetea** [comment]
I am sorry , it is wrong. I am not  familiar with the use of github.  very sorry!!!

**Comment by TSC21** [comment]
No problem ;) have you tested latest master on mavros? It now has all correct frame conversions and they are called from functions on mavros lib. You should expect to have your project working, at least on mavros side. Consider also to adjust your mc_position and mc_attitude controller gains against your vehicle so you don't have unexpected behaviors on offboard control. Also you must have your frame and motors calibrated and your propellers balanced. Try to adjust your vehicle center of mass as most as possible. Leave all the doubts you have in PX4Firmware gitter ;)
Closing this now...

**Pull request closed without merging**
